version: '3'
services:
  client:
    image: bpun1p/client:1.0
    ports:
      - 3000:3000
  server:
    image: bpun1p/server:1.0
    ports:
      - 5000:5000
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bpun1p
      - MONGO_INITDB_ROOT_PASSWORD=Guy123su
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=bpun1p
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Guy123su
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
