version: "3"

services:
    environment:
      - DOCKER_HOST=tcp://socat:2375
    links:
      - socat
  socat:
     image: bpack/socat
     command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-         
              <cont on prev line>CONNECT:/var/run/docker.sock
     volumes:
        - /var/run/docker.sock:/var/run/docker.sock
     expose:
        - "2375"